const ru = [
  {
    small: 'ё',
    shift: 'Ё',
    code: 'Backquote',
    type: 'letter',
    isFn: false,
  },
  {
    small: '1',
    shift: '!',
    code: 'Digit1',
    type: 'digit',
    isFn: false,
  },
  {
    small: '2',
    shift: '"',
    code: 'Digit2',
    type: 'digit',
    isFn: false,
  },
  {
    small: '3',
    shift: '№',
    code: 'Digit3',
    type: 'digit',
    isFn: false,
  },
  {
    small: '4',
    shift: ';',
    code: 'Digit4',
    type: 'digit',
    isFn: false,
  },
  {
    small: '5',
    shift: '%',
    code: 'Digit5',
    type: 'digit',
    isFn: false,
  },
  {
    small: '6',
    shift: ':',
    code: 'Digit6',
    type: 'digit',
    isFn: false,
  },
  {
    small: '7',
    shift: '?',
    code: 'Digit7',
    type: 'digit',
    isFn: false,
  },
  {
    small: '8',
    shift: '*',
    code: 'Digit8',
    type: 'digit',
    isFn: false,
  },
  {
    small: '9',
    shift: '(',
    code: 'Digit9',
    type: 'digit',
    isFn: false,
  },
  {
    small: '0',
    shift: ')',
    code: 'Digit0',
    type: 'digit',
    isFn: false,
  },
  {
    small: '-',
    shift: '_',
    code: 'NumpadSubtract',
    type: 'digit',
    isFn: false,
  },
  {
    small: '=',
    shift: '+',
    code: 'Equal',
    type: 'digit',
    isFn: false,
  },
  {
    small: 'Backspace',
    shift: 'Backspace',
    code: 'Backspace',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Tab',
    shift: 'Tab',
    code: 'Tab',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'й',
    shift: 'Й',
    code: 'KeyQ',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'ц',
    shift: 'Ц',
    code: 'KeyW',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'у',
    shift: 'У',
    code: 'KeyE',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'к',
    shift: 'К',
    code: 'KeyR',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'е',
    shift: 'Е',
    code: 'KeyT',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'н',
    shift: 'Н',
    code: 'KeyY',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'г',
    shift: 'Г',
    code: 'KeyU',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'ш',
    shift: 'Ш',
    code: 'KeyI',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'щ',
    shift: 'Щ',
    code: 'KeyO',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'з',
    shift: 'З',
    code: 'KeyP',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'х',
    shift: 'Х',
    code: 'BracketLeft',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'ъ',
    shift: 'Ъ',
    code: 'BracketRight',
    type: 'letter',
    isFn: false,
  },
  {
    small: '\\',
    shift: '/',
    code: 'Backslash',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'Delete',
    shift: 'Delete',
    code: 'Delete',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'CapsLock',
    shift: 'CapsLock',
    code: 'CapsLock',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'ф',
    shift: 'Ф',
    code: 'KeyA',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'ы',
    shift: 'Ы',
    code: 'KeyS',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'в',
    shift: 'В',
    code: 'KeyD',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'а',
    shift: 'А',
    code: 'KeyF',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'п',
    shift: 'П',
    code: 'KeyG',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'р',
    shift: 'Р',
    code: 'KeyH',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'о',
    shift: 'О',
    code: 'KeyJ',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'л',
    shift: 'Л',
    code: 'KeyK',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'д',
    shift: 'Д',
    code: 'KeyL',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'ж',
    shift: 'Ж',
    code: 'Semicolon',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'э',
    shift: 'Э',
    code: 'Quote',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'Enter',
    shift: 'Enter',
    code: 'Enter',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Shift',
    shift: 'Shift',
    code: 'ShiftLeft',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'я',
    shift: 'Я',
    code: 'KeyZ',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'ч',
    shift: 'Ч',
    code: 'KeyX',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'с',
    shift: 'С',
    code: 'KeyC',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'м',
    shift: 'М',
    code: 'KeyV',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'и',
    shift: 'И',
    code: 'KeyB',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'т',
    shift: 'Т',
    code: 'KeyN',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'ь',
    shift: 'Ь',
    code: 'KeyM',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'б',
    shift: 'Б',
    code: 'Comma',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'ю',
    shift: 'Ю',
    code: 'Period',
    type: 'letter',
    isFn: false,
  },
  {
    small: '.',
    shift: ',',
    code: 'Slash',
    type: 'letter',
    isFn: false,
  },
  {
    small: '&uarr',
    shift: '&uarr',
    code: 'ArrowUp',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Shift',
    shift: 'Shift',
    code: 'ShiftRight',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Ctrl',
    shift: 'Ctrl',
    code: 'ControlLeft',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Win',
    shift: 'Win',
    code: 'MetaLeft',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Alt',
    shift: 'Alt',
    code: 'AltLeft',
    type: 'fn',
    isFn: true,
  },
  {
    small: ' ',
    shift: ' ',
    code: 'Space',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'Alt',
    shift: 'Alt',
    code: 'AltRight',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Ctrl',
    shift: 'Ctrl',
    code: 'ControlRight',
    type: 'fn',
    isFn: true,
  },
  {
    small: '&larr',
    shift: '&larr',
    code: 'ArrowLeft',
    type: 'fn',
    isFn: true,
  },
  {
    small: '&darr',
    shift: '&darr',
    code: 'ArrowDown',
    type: 'fn',
    isFn: true,
  },
  {
    small: '&rarr',
    shift: '&rarr',
    code: 'ArrowRight',
    type: 'fn',
    isFn: true,
  },
];

const en = [
  {
    small: '`',
    shift: '~',
    code: 'Backquote',
    type: 'digit',
    isFn: false,
  },
  {
    small: '1',
    shift: '!',
    code: 'Digit1',
    type: 'digit',
    isFn: false,
  },
  {
    small: '2',
    shift: '@',
    code: 'Digit2',
    type: 'digit',
    isFn: false,
  },
  {
    small: '3',
    shift: '#',
    code: 'Digit3',
    type: 'digit',
    isFn: false,
  },
  {
    small: '4',
    shift: '$',
    code: 'Digit4',
    type: 'digit',
    isFn: false,
  },
  {
    small: '5',
    shift: '%',
    code: 'Digit5',
    type: 'digit',
    isFn: false,
  },
  {
    small: '6',
    shift: '^',
    code: 'Digit6',
    type: 'digit',
    isFn: false,
  },
  {
    small: '7',
    shift: '&',
    code: 'Digit7',
    type: 'digit',
    isFn: false,
  },
  {
    small: '8',
    shift: '*',
    code: 'Digit8',
    type: 'digit',
    isFn: false,
  },
  {
    small: '9',
    shift: '(',
    code: 'Digit9',
    type: 'digit',
    isFn: false,
  },
  {
    small: '0',
    shift: ')',
    code: 'Digit0',
    type: 'digit',
    isFn: false,
  },
  {
    small: '-',
    shift: '_',
    code: 'NumpadSubtract',
    type: 'digit',
    isFn: false,
  },
  {
    small: '=',
    shift: '+',
    code: 'Equal',
    type: 'digit',
    isFn: false,
  },
  {
    small: 'Backspace',
    shift: 'Backspace',
    code: 'Backspace',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Tab',
    shift: 'Tab',
    code: 'Tab',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'q',
    shift: 'Q',
    code: 'KeyQ',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'w',
    shift: 'W',
    code: 'KeyW',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'e',
    shift: 'E',
    code: 'KeyE',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'r',
    shift: 'R',
    code: 'KeyR',
    type: 'letter',
    isFn: false,
  },
  {
    small: 't',
    shift: 'T',
    code: 'KeyT',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'y',
    shift: 'Y',
    code: 'KeyY',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'u',
    shift: 'U',
    code: 'KeyU',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'i',
    shift: 'I',
    code: 'KeyI',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'o',
    shift: 'O',
    code: 'KeyO',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'p',
    shift: 'P',
    code: 'KeyP',
    type: 'letter',
    isFn: false,
  },
  {
    small: '[',
    shift: '{',
    code: 'BracketLeft',
    type: 'letter',
    isFn: false,
  },
  {
    small: ']',
    shift: '}',
    code: 'BracketRight',
    type: 'letter',
    isFn: false,
  },
  {
    small: '\\',
    shift: '|',
    code: 'Backslash',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'Delete',
    shift: 'Delete',
    code: 'Delete',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'CapsLock',
    shift: 'CapsLock',
    code: 'CapsLock',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'a',
    shift: 'A',
    code: 'KeyA',
    type: 'letter',
    isFn: false,
  },
  {
    small: 's',
    shift: 'S',
    code: 'KeyS',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'd',
    shift: 'D',
    code: 'KeyD',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'f',
    shift: 'F',
    code: 'KeyF',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'g',
    shift: 'G',
    code: 'KeyG',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'h',
    shift: 'H',
    code: 'KeyH',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'j',
    shift: 'J',
    code: 'KeyJ',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'k',
    shift: 'K',
    code: 'KeyK',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'l',
    shift: 'L',
    code: 'KeyL',
    type: 'letter',
    isFn: false,
  },
  {
    small: ';',
    shift: ':',
    code: 'Semicolon',
    type: 'letter',
    isFn: false,
  },
  {
    small: "'",
    shift: '"',
    code: 'Quote',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'Enter',
    shift: 'Enter',
    code: 'Enter',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Shift',
    shift: 'Shift',
    code: 'ShiftLeft',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'z',
    shift: 'Z',
    code: 'KeyZ',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'x',
    shift: 'X',
    code: 'KeyX',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'c',
    shift: 'C',
    code: 'KeyC',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'v',
    shift: 'v',
    code: 'KeyV',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'b',
    shift: 'B',
    code: 'KeyB',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'n',
    shift: 'N',
    code: 'KeyN',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'm',
    shift: 'M',
    code: 'KeyM',
    type: 'letter',
    isFn: false,
  },
  {
    small: ',',
    shift: '<',
    code: 'Comma',
    type: 'letter',
    isFn: false,
  },
  {
    small: '.',
    shift: '>',
    code: 'Period',
    type: 'letter',
    isFn: false,
  },
  {
    small: '/',
    shift: '?',
    code: 'Slash',
    type: 'letter',
    isFn: false,
  },
  {
    small: '&uarr',
    shift: '&uarr',
    code: 'ArrowUp',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Shift',
    shift: 'Shift',
    code: 'ShiftRight',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Ctrl',
    shift: 'Ctrl',
    code: 'ControlLeft',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Win',
    shift: 'Win',
    code: 'MetaLeft',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Alt',
    shift: 'Alt',
    code: 'AltLeft',
    type: 'fn',
    isFn: true,
  },
  {
    small: ' ',
    shift: ' ',
    code: 'Space',
    type: 'letter',
    isFn: false,
  },
  {
    small: 'Alt',
    shift: 'Alt',
    code: 'AltRight',
    type: 'fn',
    isFn: true,
  },
  {
    small: 'Ctrl',
    shift: 'Ctrl',
    code: 'ControlRight',
    type: 'fn',
    isFn: true,
  },
  {
    small: '&larr',
    shift: '&larr',
    code: 'ArrowLeft',
    type: 'fn',
    isFn: true,
  },
  {
    small: '&darr',
    shift: '&darr',
    code: 'ArrowDown',
    type: 'fn',
    isFn: true,
  },
  {
    small: '&rarr',
    shift: '&rarr',
    code: 'ArrowRight',
    type: 'fn',
    isFn: true,
  },

];

export { ru, en };
